name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version
      
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew build
